# IBM MQ
ibm.mq.host=localhost
ibm.mq.port=1414
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.queueManagerName=QM1
ibm.mq.user=app

# ActiveMQ
activemq.brokerURL=tcp://localhost:61616
activemq.user=admin
activemq.password=admin

# WMON queue names
mq.wmon.cost.queue.name=WMON.COST
mq.wmon.tracking.queue.name=WMON.TRACKING
mq.wmon.notices.queue.name=WMON.NOTICES
mq.wmon.shipment.queue.name=WMON.SHIPMENT
mq.wmon.shipment.track.queue.name=WMON.SHIPMENT.TRACK
